# Generated by Django 5.0.1 on 2024-02-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='reportado por')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono')),
                ('approved', models.BooleanField(default=False, verbose_name='aprobado')),
                ('photo', models.ImageField(upload_to='potholes/', verbose_name='foto')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
