# Generated by Django 5.0.1 on 2024-06-05 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_potholes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='icono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pothole',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pothole',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pothole',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_potholes.category'),
        ),
        migrations.CreateModel(
            name='PotholeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pothole_images/')),
                ('pothole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='report_potholes.pothole')),
            ],
        ),
    ]
