# Generated by Django 5.0.1 on 2024-06-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_potholes', '0002_category_pothole_title_alter_pothole_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='year_management',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gestión'),
        ),
    ]
