# Generated by Django 5.0.1 on 2024-06-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_potholes', '0003_pothole_year_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='pothole',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
    ]
