# Generated by Django 5.0.1 on 2025-07-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_potholes', '0004_pothole_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_picons/', verbose_name='icono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre')),
                ('organization', models.TextField(blank=True, null=True, verbose_name='organización')),
                ('province', models.CharField(choices=[('cercado', 'Cercado'), ('vacadiez', 'Vaca Díez'), ('ballivian', 'Ballivián'), ('yacuma', 'Yacuma'), ('moxos', 'Moxos'), ('marban', 'Marbán'), ('mamore', 'Mamoré'), ('itenez', 'Iténez')], default='cercado', max_length=20, verbose_name='Provincia')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('photo', models.ImageField(upload_to='agent/', verbose_name='foto')),
                ('year_management', models.IntegerField(blank=True, null=True, verbose_name='Gestión')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_potholes.categoryprivate')),
            ],
        ),
    ]
