# Generated by Django 5.0.1 on 2026-02-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_potholes', '0005_categoryprivate_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pothole',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='potholes/', verbose_name='foto'),
        ),
    ]
